"""
Configuration module for the Medical Survival Analysis Pipeline.

This file manages file paths and global settings.
It is designed to work with 'utils/auto_schema.py' for variable detection.
"""

from pathlib import Path

# =============================================================================
# 1. PATH MANAGEMENT
# =============================================================================
# Resolves to the project root regardless of OS (Windows/Linux/Mac)
BASE_DIR = Path(__file__).resolve().parent.parent
DATA_PATH = BASE_DIR / "data"
LOGS_PATH = BASE_DIR / "logs"

# Ensure logs directory exists
LOGS_PATH.mkdir(parents=True, exist_ok=True)

# =============================================================================
# 2. DATA FILES
# =============================================================================
# Raw file provided by the researcher (e.g., "breast_cancer.csv")
SOURCE_FILE = "lung_cancer.csv"

# Files generated by the split script (and read by load_data)
TRAIN_FILE = "dataset_train.csv"
TEST_FILE = "dataset_test.csv"

# Split ratio (20% for test is standard)
TEST_SIZE = 0.2

# =============================================================================
# 3. SCHEMA OVERRIDES (Optional)
# =============================================================================
# By default, set these to None. The SchemaDetector will find them automatically.
# ONLY fill these if the auto-detection fails or picks the wrong columns.

OVERRIDE_SCHEMA = {
    # Force specific column names for Time and Event
    "duration_col": None,  # e.g., "survival_months"
    "event_col": None,  # e.g., "death_event"
    # Force specific lists of features (lists of strings)
    # Useful if you want to exclude specific columns that aren't IDs but are noise.
    "numerical_cols": None,
    "categorical_cols": None,
    # Force columns to be dropped (e.g., internal hospital IDs, comments)
    "dropped_cols": ["TIME0"],
}

# =============================================================================
# 4. GLOBAL PARAMETERS
# =============================================================================
RANDOM_SEED = 42

# Thresholds for heuristic detection in auto_schema.py
# If a numerical column has < 5% unique values, it might be categorical.
CATEGORICAL_THRESHOLD_RATIO = 0.05
CATEGORICAL_THRESHOLD_COUNT = 10
